#! /bin/sh


padding=0
gap=5
border=2

#deadd-notification-center &
#compton --experimental-backends &
picom --experimental-backends &

nitrogen --restore

killall sxhkd
sxhkd &


killall polybar
polybar &


killall picom
picom &

cd shells
./autostart.sh &

cd ..


# MONITOR
bspc monitor HDMI-1 -d  I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X


# CUSTOM
bspc config focused_border_color  "#928374"
bspc config normal_border_color  "#1B1B1B"
bspc config border_width         $border
bspc config window_gap           $gap
bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true
bspc config focus_follows_pointer true
bspc config bottom_padding  $padding
bspc config top_padding     $padding
bspc config left_padding    $padding
bspc config right_padding   $padding
bspc config directional_focus_tightness low


# Remove x cursor
xsetroot -cursor_name left_ptr &


# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^1'
bspc rule -a discord desktop='^4' follow=on
bspc rule -a obs desktop='^5' follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating rectangle 800x800 sticky=off
bspc rule -a ghost-chat state=floating border=off sticky=on


#enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1


killall bspswallow
fipgrep -f $HOME/.config/bspwm/swallow || $HOME/.config/bspwm/bspswallow &
